### ISSUE TITLE
NodeViewHolder class does not exist?

### ISSUE THREAD

**Issue by BrayanOB2003** [Team-Blox/TreeView#81]
When I try to implement the library, the NodeViewHolder class is not instantiated. Is it a class that I have to create myself?

**Comment by GregorBlock** [comment]
Hi @BrayanOB2003, yes since GraphView is built on top of RecyclerView you need [ViewHolders](https://developer.android.com/reference/androidx/recyclerview/widget/RecyclerView.ViewHolder) like in this case a NodeViewHolder which is derived from RecyclerView.ViewHolder.  And there you bind the data which should be displayed.
